name: Rust CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  merge_group:

jobs:
  build:
    name: Rust Integration CI LLVM ${{ matrix.llvm }} ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [openstack22]

    timeout-minutes: 600
    steps:
      - name: checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: dtolnay/rust-toolchain@nightly
      - name: build
        run: |
          mkdir build
          cd build
          ../configure --enable-llvm-link-shared --enable-llvm-plugins --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-lld --enable-option-checking --enable-ninja --disable-docs
          ../x.py build --stage 1 library/std library/proc_macro library/test tools/rustdoc
          rustup toolchain link enzyme `pwd`/build/`rustup target list --installed`/stage1
      - name: test
        run: |
          cargo +enzyme test --examples
