name: Rust CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  merge_group:

jobs:
  build:
    name: Rust Integration CI LLVM ${{ matrix.llvm }} ${{ matrix.build }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [openstack22]

    timeout-minutes: 600
    steps:
      - name: Checkout Rust source
        uses: actions/checkout@v4
        with:
          submodules: true # check out all submodules so the cache can work correctly
          fetch-depth: 2
      - uses: dtolnay/rust-toolchain@nightly
      - name: Get LLVM commit hash
        id: llvm-commit
        run: echo "HEAD=$(git rev-parse HEAD:src/llvm-project)" >> $GITHUB_OUTPUT
      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: build/build/x86_64-unknown-linux-gnu/llvm
          key: ${{ matrix.os }}-llvm-${{ steps.llvm-commit.outputs.HEAD }}
      - name: Get Enzyme commit hash
        id: enzyme-commit
        run: echo "HEAD=$(git rev-parse HEAD:src/tools/enzyme)" >> $GITHUB_OUTPUT
      - name: Cache Enzyme
        id: cache-enzyme
        uses: actions/cache@v4
        with:
          path: build/build/x86_64-unknown-linux-gnu/enzyme
          key: ${{ matrix.os }}-enzyme-${{ steps.enzyme-commit.outputs.HEAD }}
      - name: Build
        run: |
          mkdir -p build
          cd build
          rm -f config.toml
          ../configure --enable-llvm-link-shared --enable-llvm-plugins --enable-llvm-enzyme --release-channel=nightly --enable-llvm-assertions --enable-lld --enable-option-checking --enable-ninja --disable-docs
          ../x.py build --stage 1 library/std library/proc_macro library/test tools/rustdoc
          rustup toolchain link enzyme build/host/stage1
      - name: checkout Enzyme/rustbook
        uses: actions/checkout@v4
        with:
          repository: EnzymeAD/rustbook
          ref: main
          path: rustbook
      - name: test Enzyme/rustbook
        working-directory: rustbook
        run: |
          cargo +enzyme test
          cargo +enzyme test -p samples-loose-types
